### ISSUE TITLE
[Investigate] Use on the invoice the same customer details as the ones on the proforma

### ISSUE THREAD

**Issue by zalmanu** [PressLabs/silver#287]

**Comment by bogdanpetrea** [comment]
What is to investigate here?

**Comment by zalmanu** [comment]
1) When a proforma is issued the details of the customer should be copied into `archived_customer`
2) If a proforma is paid and the provider's flow is `proforma`, when creating the invoice automatically, it should copy the archived details of the customer and use those instead of retrieving the details from the related customer object. The details might have changed and we should keep the ones from the proforma. 

These 2 aspects should be investigated as they are related and `2)` does not work without `1)`.

**Comment by bogdanpetrea** [comment]
1) and 2) are already happening.

A new one:
3) When the document entries are generated we need to make sure the generator uses the frozen details (such as sales_tax_percent and sales_tax_name) and not the ones from the related customer object.
