### ISSUE TITLE
Django 1.9

### ISSUE THREAD

**Issue by Alexx-G** [PressLabs/silver#293]
Current stable version of Django is 1.9.2.
Django 1.9 has some nice features (new lookups, new core features, improved template engine etc) and bug fixes.
Do you have any plans to support Django 1.9?
Also, why are you using `django-international`? This package is pre-alpha and last update was in 2014. This can create some problems for update to newer version of Django.

Any reasons why this package depends of Django 1.8.3? The latest version of Django 1.8 is 1.8.9.

**Comment by zalmanu** [comment]
Hi @Alexx-G,

Thanks for your interest in the project. I will answer your questions in order: 
* We don't have planned an official upgrade to Django 1.9 but we do hope to upgrade at some point. However, we are more than pleased to accept contributions to the project, upgrades included. Thus, if you are interested please send a pull request with the upgraded version and we will do our best to merge it.
* We use `django-international` to generate the `choices` option for the countries and currencies in some of the models. So far it has been working fine.
* We froze the Django version at `1.8.3` but we plan on doing the upgrade to `1.8.9` as soon as possible. Again, if you find this interesting, we would be more than happy to accept your contribution.
