### ISSUE TITLE
Add an order field to metered feature

### ISSUE THREAD

**Issue by macmichael01** [PressLabs/silver#321]
When displaying a group of plan with a given set of features, it would be nice if there was an order field for display purposes and perhaps a flag which determines whether that feature is enabled for that.

Plan 1
- Feature 1 (Included)
- Feature 2 (Included)
- Feature 3 (not-included)

Plan 2
- Feature 1 (Included)
- Feature 2 (Included)
- Feature 3 (included)

I see the order field (and perhaps the is_enabled flag field) as a field that could be added to the MeaturedFeature model or a part of the Intermediate table between Plans and Metered Features.

**Comment by bogdanpetrea** [comment]
Hi @macmichael01,
I assume you are talking about displaying the group of plans in a custom template / view.

The absence of a metered feature from a plan means it is not included so you can make comparisons between the 2 plans when rendering the template / view. For example mark Feature X as not-included if it only shows up in the first plan.

As for ordering the features, there are many ways you can do this as well when rendering the template / view. It just depends on how you want to order them. 
By default I think they are ordered by their id. For example you can sort them by name, unit, product_code etc. by calling `order_by` on a feature queryset or by using the `sorted` function.

Hope this helped.

**Comment by macmichael01** [comment]
Cool thanks. That should work. Closing this ticket.
