### ISSUE TITLE
Find a replacement for django-international (no update in 2+ years)

### ISSUE THREAD

**Issue by bogdanpetrea** [PressLabs/silver#324]
Reason: https://github.com/PressLabs/silver/issues/322

Possible solutions:
https://pypi.python.org/pypi/pycountry
https://pypi.python.org/pypi/django-countries

**Comment by AMecea** [comment]
What about: [pycountry](https://bitbucket.org/flyingcircus/pycountry/overview) this one has both countries and currencies.
