### ISSUE TITLE
How can I use silver for single-time invoicing?

### ISSUE THREAD

**Issue by mishu-** [PressLabs/silver#340]
Right now silver is built on a subscription model. You have a customer which subscribed to a monthly service and he makes recurring payments. I want to use it in a system where the customer only pays once and I only generate one invoice for him. I don't really need the overhead of setting up a subscription.

Thanks!

cc @bogdanpetrea

**Comment by bogdanpetrea** [comment]
Hi @mishu. If you don't need a subscription, you'll have to manually create the Invoice, create some entries for it and issue it.

```
invoice = Invoice.objects.create(customer=customer, provider=provider, [...])
DocumentEntry.objects.create(description="2cup Raspberry Ice Cream",
                             quantity=1,
                             unit_price=0.99,
                             invoice=invoice)
invoice.issue()
```

I realize now a Invoice.add_entry method would be nice.
Hope this helps.
