### ISSUE TITLE
Transaction valid_until can't compare to none type

### ISSUE THREAD

**Issue by krodyrobi** [PressLabs/silver#354]
http://127.0.0.1:8000/customers/1/payment_methods/1/transactions/

Again the user does not seem to matter on the transaction if he is the owner of the payment_method. All combinations produce the same thing.

```
/silver/silver/models/transactions.py in s_usable
          self.valid_until > timezone.now() 
```

If the field valid_until is set we are ok, so I propose to make it not nullable.

**Comment by bogdanpetrea** [comment]
Do you have a proper log?

**Comment by krodyrobi** [comment]
Create a customer + a payment for the user then try and add a transaction without a valid_until from the admin. Unless filled in with a date this error will pop up. Forgot to screencapture.

**Comment by krodyrobi** [comment]
Apparently on the master branch this is not happening anymore. Or the steps to reproduce are deeper than I thought. Closing for now.
