### ISSUE TITLE
Transaction filtered by an undefined payment_processor fails

### ISSUE THREAD

**Issue by krodyrobi** [PressLabs/silver#370]
```
File "/home/krotz/workspace/silver/silver/api/views.py", line 894, in get_queryset
    if not payment_method.payment_processor.transaction_class:
AttributeError: 'unicode' object has no attribute 'transaction_class'
```

**Comment by bogdanpetrea** [comment]
Next time please provide the steps to reproduce as well, because the code changes in time.

**Comment by bogdanpetrea** [comment]
This was probably fixed with https://github.com/PressLabs/silver/pull/423, as in it works now. But the parameter name needs to be changed from payment_method to payment_processor, because it's named wrong in the TransactionFilter.
